[env_params]
stage_cnt = 3
machine_cnt_list = [4, 4, 4]
job_cnt = 20
process_time_low = 2
process_time_high = 10
pomo_size = 24

[model_params]
stage_cnt = 3
machine_cnt_list = [4, 4, 4]
embedding_dim = 256
sqrt_embedding_dim = 16
encoder_layer_num = 3
qkv_dim = 16
sqrt_qkv_dim = 4
head_num = 16
logit_clipping = 10
ff_hidden_dim = 512
ms_hidden_dim = 16
ms_layer1_init = (1/2)**(1/2)
ms_layer2_init = 0.25
eval_type = 'argmax'
one_hot_seed_cnt = 4

[optimizer_params]
lr = 1e-4
weight_decay = 1e-6
milestones = [101, 151]
gamma = 0.1

[trainer_params]
use_cuda = True
cuda_device_num = 0
epochs = 100
train_episodes = 1000
train_batch_size = 50
model_save_interval = 100
img_save_interval = 100
json_foldername = 'log_image_style'
filename1 = 'style.json'
filename2 = 'style_loss.json'
enable = False

[logger_params]
desc = 'matnet_train'
filename = 'log.txt'
